# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build with Gradle

on:
  push:
    branches: [ main, develop, graalvm-fulldata ]
  pull_request:
    branches: [ main, develop, graalvm-fulldata ]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
       matrix:
          java: [ 17, 21 ]
       fail-fast: false
    name: Java ${{ matrix.java }} sample
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Build precision-experiments
      run: cd /home/runner/work/precision-experiments/precision-experiments/ && ./gradlew assemble -x test
    - name: Build precision-analysis
      run: cd /home/runner/work/precision-experiments/precision-experiments/precision-analysis/ && ../gradlew test publishToMavenLocal
    - name: Publish Test Report
      if: ${{ always() }}      
      uses: scacap/action-surefire-report@v1
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
